# Generated by Django 4.1.3 on 2023-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='actions',
            field=models.CharField(max_length=200),
        ),
    ]
