# Generated by Django 4.1.3 on 2023-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='endslot',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.TimeField(null=True),
        ),
    ]
