# Generated by Django 4.1.3 on 2022-11-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectlevel', models.CharField(choices=[('higher', 'Higher'), ('oridinary', 'Oridinary'), ('foundation', 'Foundation')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('point', models.IntegerField()),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade', to='calculator.level')),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('is_additional_marks_allowed', models.BooleanField(default=False)),
                ('additional_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.ManyToManyField(blank=True, related_name='subject_level', to='calculator.level')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
